export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_ATTEMPTS_EXCEEDED: 'OTP_ATTEMPTS_EXCEEDED',
  OTP_RESEND_COOLDOWN: 'OTP_RESEND_COOLDOWN',
  SEAT_ALREADY_RESERVED: 'SEAT_ALREADY_RESERVED',
  SEAT_LAYOUT_VERSION_MISMATCH: 'SEAT_LAYOUT_VERSION_MISMATCH',
  RESERVATION_LIMIT_EXCEEDED: 'RESERVATION_LIMIT_EXCEEDED',
  CANCELLATION_NOT_ALLOWED: 'CANCELLATION_NOT_ALLOWED',
  ALREADY_CANCELLED: 'ALREADY_CANCELLED',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const

type ErrorCodeKey = keyof typeof ErrorCode

const HTTP_STATUS: Record<ErrorCodeKey, number> = {
  VALIDATION_ERROR: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  OTP_EXPIRED: 422,
  OTP_INVALID: 422,
  OTP_ATTEMPTS_EXCEEDED: 429,
  OTP_RESEND_COOLDOWN: 429,
  SEAT_ALREADY_RESERVED: 409,
  SEAT_LAYOUT_VERSION_MISMATCH: 409,
  RESERVATION_LIMIT_EXCEEDED: 422,
  CANCELLATION_NOT_ALLOWED: 422,
  ALREADY_CANCELLED: 422,
  INTERNAL_SERVER_ERROR: 500,
}

export class AppError extends Error {
  readonly code: ErrorCodeKey
  readonly status: number
  readonly details?: unknown

  constructor(code: ErrorCodeKey, message: string, details?: unknown) {
    super(message)
    this.name = 'AppError'
    this.code = code
    this.status = HTTP_STATUS[code]
    this.details = details
  }
}
